### ISSUE TITLE
Error Most middleware (like bodyparser)

### ISSUE THREAD

**Issue by blackvampire231** [martindale/snarl#51]
whenever i try and run the bot.js this error comes up

Error: Most middleware (like bodyParser) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.Object.defineProperty.get (C:\snarl-master\node_modules\express\lib\express.js:89:13)
    at Object.<anonymous> (C:\snarl-master\bot.js:109:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

idk what to do and would appreciate a little help thanks

**Comment by cismanish** [comment]
Not working for me, Can you please help to resolve this issue

**Comment by cismanish** [comment]
Not working for me, Can you please help to resolve this issue

**Comment by martindale** [comment]
Sure, @chinseone!  What error are you getting currently?

**Comment by martindale** [comment]
Resolved with #73.  Please open a new issue if you run into a problem!
